<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: levi
 * Date: Fri, 17 Mar 2023 14:09:40 +0100
 */

$conf['title'] = '';
$conf['lang'] = 'pt-br';
$conf['template'] = 'bootstrap3';
$conf['license'] = 'cc-by-sa';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['defer_js'] = 0;
$conf['proxy']['user'] = 'admin';
$conf['proxy']['pass'] = '<b>UG9jb3Bob25lQDIwMjI=';
$conf['plugin']['icons']['loadTypicons'] = 1;
$conf['plugin']['icons']['loadFontlinux'] = 1;
$conf['plugin']['icons']['loadRpgAwesome'] = 1;
$conf['plugin']['indexmenu']['hide_headpage'] = 0;
$conf['tpl']['bootstrap3']['showUserHomeLink'] = 0;
$conf['tpl']['bootstrap3']['showSearchForm'] = 'never';
$conf['tpl']['bootstrap3']['navbarLabels'] = 'login,register,admin';
$conf['tpl']['bootstrap3']['fluidContainer'] = 0;
$conf['tpl']['bootstrap3']['tableFullWidth'] = 0;
$conf['tpl']['bootstrap3']['showPageId'] = 0;
$conf['tpl']['bootstrap3']['showWikiInfo'] = 0;
$conf['tpl']['bootstrap3']['socialShareProviders'] = 'facebook,linkedin,microsoft-teams,pinterest,whatsapp,reddit,twitter,telegram,yammer,google-plus';
