# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Wed, 08 Mar 2023 18:30:01 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

levi:$2y$10$HlIfYLztgk2Yr4Lo201UNeku3O52XA6wADNrrni5MJ/lDYdsVTt7a:Levi Lucena:sr_lucen@yahoo.com.br:admin,user
